[pytest]
testpaths = tests
python_files = test_*.py array_*.py long_*.py
python_classes = Test*
python_functions = test_*
addopts = --import-mode=importlib
markers =
    dense: marks tests to run with dense array settings
    sparse: marks tests to run with sparse array settings
